name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build -t naufalamri/dumbflix-backend:latest .

    - name: Docker Login
      uses: docker/login-action@v3
      with:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Push
    run: docker push naufalamri/dumbflix-backend:latest


